### ISSUE TITLE
Addon is not listed when previously set them to invisible on steam.

### ISSUE THREAD

**Issue by opti2000** [Leeous/gmod-addon-tool#10]
Hi there, i tried to update an existing addon and made it invisible but when i started the program and pressed on update existing addon its not in the list anymore but all my other addons are still there even though i set that addon back to visible.

I tested this with 2 other addons. I set them to invisible and pressed update existing addon and they are not listed anymore. Setting the addons back to visible doesnt do anything and you cant update those addons because i cant select them anymore in the list.

**Comment by Leeous** [comment]
Gotcha, I'll look into this as soon as possible. Would you mind sharing your log? Click the settings cog, then "View Console Log". I just need to see the last 10 lines or so.

**Comment by Leeous** [comment]
@opti2000 I misread your issue, the addon must be set to public to update it. That's why they're not showing up.

**Comment by opti2000** [comment]
Hello sorry, was a bit busy. Unfortunately i cant post a log because the program says `couldnt find gmod-addon-tool\resources\app.asar/log.txt`

Also i set the addons back to public but i cant see them in GMAT.

**Comment by Leeous** [comment]
What install method did you choose? Portable, or install?

**Comment by opti2000** [comment]
I installed it

**Comment by Leeous** [comment]
Gotcha, try using the portable version if you don't mind. Just so we can see what `gmpublish` is doing when you attempt to update your addons.
