### ISSUE TITLE
Infinite loading problem already existing addon bug

### ISSUE THREAD

**Issue by DevCad** [Leeous/gmod-addon-tool#17]
I have the same issue as #11 

In the logs it finds the addons, but never loads them.

I have tried updated three times and the issue is still there.

![Capture](https://user-images.githubusercontent.com/53978081/98486657-58928b80-2227-11eb-9ab6-d1fd3cdb9b87.PNG)

**Comment by DevCad** [comment]
![Capture](https://user-images.githubusercontent.com/53978081/98486639-339e1880-2227-11eb-9527-71fd6453dc88.PNG)

**Comment by Leeous** [comment]
Hey @DevCad! Sorry, I was on vacation. I'm working on v2.3 at the moment and I'm fairly competent that it will fix your issue,  I can send you a build if you'd like to test it out. I am also working on a debug switch that will allow more concise and complete logs. I don't really know what causes this error and I haven't been able to reproduce it on my machine. If you would answer a few things so I can see what the recurring traits of this bug are, that would help a lot.

Have you always had this bug?
How many addons do you have?
Is this your first addon?
Are you sure your addon passes the [file verification process](https://wiki.facepunch.com/gmod/Workshop_Addon_Creation#preparingyouraddon)?

**Comment by ZachTaMere** [comment]
I have the same bug.

**Comment by Leeous** [comment]
@ZachTaMere if you can, please answer these questions

Have you always had this bug?
How many addons do you have?
Is this your first addon?
Are you sure your addon passes the file verification process?

**Comment by ZachTaMere** [comment]
I have this bug seen i install your software ( 2 weeks )
I have 4 addons
No it's not my first addon
Ye my addon passes the file verification process.

**Comment by Leeous** [comment]
> I have this bug seen i install your software ( 2 weeks )
> I have 4 addons
> No it's not my first addon
> Ye my addon passes the file verification process.
> 

Thanks! There's a new release coming out in two days that should fix your issue. :)
