### ISSUE TITLE
Loading...

### ISSUE THREAD

**Issue by Sentryandreas** [Leeous/gmod-addon-tool#2]
So.. It was pretty fine until I've updated my last addon, but today when I tried to update my new addon, the uploading tool just stucked with "Loading..." text. Even I tried restart my whole computer and Steam, Still not working. Is this because of new workshop update of Gmod yesterday?
![bandicam 2020-01-22 18-53-58-281](https://user-images.githubusercontent.com/59036487/72884917-4a33bb80-3d4a-11ea-9ffe-e25eb1bbc605.jpg)

**Comment by Leeous** [comment]
I'll take a look at the issue when I get home. Could you provide whatever errors, if any, are popping up? You can access the console with <Ctrl+Shift+I>

**Comment by Leeous** [comment]
If it is due to an update to Garry's Mod, I'll provide a fix ASAP.

**Comment by Leeous** [comment]
> Please note that new or updated addon files will no longer be stored in your addons/ folder, instead they will be stored by Steam in steamapps/workshop/ folder of your Steam game library.

This may have something to do with my tool not working.

**Comment by Leeous** [comment]
@Sentryandreas, [v1.2](https://github.com/Leeous/gmod-addon-tool/releases/tag/v1.2) should fix your problem. 😄 Reopen the issue if it doesn't.

**Comment by Sentryandreas** [comment]
It's working pretty well on your new version of Updater! I really appreciate that, Thank you. :D
The best uploader tool ever for sure! 
-----Original Message-----
