### ISSUE TITLE
Infinitely creating a GMA

### ISSUE THREAD

**Issue by cumslut65** [Leeous/gmod-addon-tool#33]
When I do all the steps to make an addon I hit 'create GMA and publish', and it infinitely says its creating the gma

**Comment by Leeous** [comment]
What type of addon is it and how large is it? 

If you don't mind, I'd like to see the console when it gets to that point of indefinite loading. Just hit `Ctrl`+`Shift`+`i` and take a screenshot of the console tab, that would help a lot.

**Comment by JJettasJR** [comment]
Hey my gma just keeps loading im on linux
