### ISSUE TITLE
Infinite Loading

### ISSUE THREAD

**Issue by g3n3r1c-u53rn4m3** [Leeous/gmod-addon-tool#35]
Whenever I try to update my addons, it just loads on and on and on and on!
<img width="371" alt="infinite" src="https://user-images.githubusercontent.com/112830178/188334947-248502fb-ef85-48ef-86b6-5b4466040d86.png">

**Comment by Leeous** [comment]
Please include the console output. You can do this by opening GMAT and hitting `Ctrl` + `Shift` + `i` and clicking the console tab.

**Comment by g3n3r1c-u53rn4m3** [comment]
Nevermind, it was fixed now. My guess is that when it did that it was because I didn't have any workshop uploads previously. Sorry for wasting your time.

**Comment by Leeous** [comment]
Glad it was resolved, and yeah! I thought I had coded it to display a message for that situation, I'll have to double check. Thanks for taking the time to create an issue.
