### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by SaintofDiablo** [Leeous/gmod-addon-tool#7]
it doesn't actually upload. it would say it worked , and brings me to a page that says the addon was removed by owner

**Comment by Leeous** [comment]
I gotcha, I think the current build has fixed this bug, but I'll look into it ASAP. If you would, make sure you check your Steam Workshop page to see if it may just be sending you to the wrong URL. :)

**Comment by Leeous** [comment]
This is fixed in [v2.0](https://github.com/Leeous/gmod-addon-tool/releases/tag/v2.0)! Try it out. 😃
