### ISSUE TITLE
Cant update workshop stuff

### ISSUE THREAD

**Issue by DreS0X** [Leeous/gmod-addon-tool#9]
I can only see and edit 2 workshop objects in the tool. The one I want to edit does not appear, as well as 3 others that should theoretically still appear there.
![Unbenannt](https://user-images.githubusercontent.com/40367513/89103398-f0efc780-d411-11ea-9bf5-fc730f383a88.png)
![Unbenannt2](https://user-images.githubusercontent.com/40367513/89103399-f1885e00-d411-11ea-9e95-c5c9089c57e2.png)

**Comment by Leeous** [comment]
Are those three addons public?

**Comment by DreS0X** [comment]
> Are those three addons public?

Yep

**Comment by Leeous** [comment]
Can you paste the console log by clicking on the settings cog, click "View Console Log", and paste about the last 20 lines?

**Comment by DreS0X** [comment]
The program does not write a log file, or I do not know where it is stored
![image](https://user-images.githubusercontent.com/40367513/89124693-362afc80-d4d9-11ea-897b-86f00b4a0bc9.png)

**Comment by Leeous** [comment]
This might be a bug due to either the location of GMAT, or the fact that your PC's language is set to German. I'll do some testing ASAP, I would suggest either using [v1.4](https://github.com/Leeous/gmod-addon-tool/releases/tag/v1.4) until I can find a fix for it. Just to be clear, those addons have to be set on public for you to update them, that may change later.

**Comment by DreS0X** [comment]
Thanks a lot for the effort you put into it, The design is just really nicer than all the other current tools. So I'm so sorry to cause you such trouble <3
I'm pretty sure that at least 3 of my workshop objects are public, but if you want to make sure, here is the link to my objects. https://steamcommunity.com/id/DreS0X/myworkshopfiles/?appid=4000

**Comment by DreS0X** [comment]
The previous version also only shows me the other two objects. Very very strange.
![image](https://user-images.githubusercontent.com/40367513/89125664-48f4ff80-d4e0-11ea-8441-b3e8ab4eaaf5.png)

**Comment by Leeous** [comment]
Thank you, I appreciate it! And it's no bother. 😁 I would suggest redownloading GMAT (w/o the installer), which can be found [here](https://github.com/Leeous/gmod-addon-tool/releases/download/v2.0/GMAT-Winx64-Portable.zip) and placing it somewhere temporary, such as your desktop, downloads, documents, etc. Could you also take a screenshot of the Chrome console while you're on the addon's page? You can open it by pressing `Ctrl` + `Shift` + `I`.
![DAdtwADebw](https://user-images.githubusercontent.com/6354807/89124689-e4697e80-d4a6-11ea-9979-71438d36d1e5.gif)
